// Catalogo statico delle posizioni Ashtanga (saluto al sole, sequenza in
// piedi, prima serie, sequenza finale) e delle relative icone. Le pose sono
// un elenco tradizionale sostanzialmente fisso: per questo il catalogo vive
// nel codice, mentre le sequenze salvate (vedi data.ts) memorizzano solo gli
// scostamenti dal default (pose disattivate + note) e restano quindi
// coerenti anche se in futuro si corregge un nome o un'icona qui.
export type AshtangaSectionKey = "sun" | "standing" | "primary" | "finishing";

export const ASHTANGA_SECTIONS: { key: AshtangaSectionKey; label: string; poses: string[] }[] = [
  {
    key: "sun",
    label: "Saluto al sole",
    poses: ["Surya Namaskara A", "Surya Namaskara B"],
  },
  {
    key: "standing",
    label: "Sequenza in piedi",
    poses: [
      "Padangusthasana", "Padahastasana", "Utthita Trikonasana", "Parivritta Trikonasana",
      "Utthita Parsvakonasana", "Parivritta Parsvakonasana",
      "Prasarita Padottanasana A", "Prasarita Padottanasana B", "Prasarita Padottanasana C", "Prasarita Padottanasana D",
      "Parsvottanasana",
      "Utthita Hasta Padangusthasana A", "Utthita Hasta Padangusthasana B", "Utthita Hasta Padangusthasana C", "Utthita Hasta Padangusthasana D",
      "Ardha Baddha Padmottanasana", "Utkatasana", "Virabhadrasana A", "Virabhadrasana B",
    ],
  },
  {
    key: "primary",
    label: "Prima serie",
    poses: [
      "Dandasana", "Paschimottanasana A", "Paschimottanasana B", "Paschimottanasana C",
      "Purvottanasana", "Ardha Baddha Padma Paschimottanasana", "Trianga Mukhaikapada Paschimottanasana",
      "Janu Sirsasana A", "Janu Sirsasana B", "Janu Sirsasana C",
      "Marichyasana A", "Marichyasana B", "Marichyasana C", "Marichyasana D",
      "Navasana (5 volte)", "Bhujapidasana", "Kurmasana", "Supta Kurmasana",
      "Garbha Pindasana", "Kukkutasana", "Baddha Konasana A", "Baddha Konasana B",
      "Upavishta Konasana A", "Upavishta Konasana B", "Supta Konasana",
      "Supta Padangusthasana A", "Supta Padangusthasana B", "Supta Padangusthasana C",
      "Ubhaya Padangusthasana", "Urdhva Mukha Paschimottanasana", "Setu Bandhasana",
    ],
  },
  {
    key: "finishing",
    label: "Sequenza finale",
    poses: [
      "Urdhva Dhanurasana (3 volte)", "Paschimottanasana", "Sarvangasana", "Halasana",
      "Karnapidasana", "Urdhva Padmasana", "Pindasana", "Matsyasana", "Uttana Padasana",
      "Sirsasana A", "Sirsasana B", "Baddha Padmasana", "Padmasana", "Tolasana", "Savasana",
    ],
  },
];

export const ALL_ASHTANGA_POSES: string[] = ASHTANGA_SECTIONS.flatMap((s) => s.poses);

// nome posa -> file in public/asanas (estratti da asana-icone-viola.zip,
// mappatura 1:1 secondo il manifest.csv originale).
export const POSE_ICON: Record<string, string> = {
  "Padangusthasana": "/asanas/01_padangusthasana.png",
  "Padahastasana": "/asanas/02_padahastasana.png",
  "Utthita Trikonasana": "/asanas/03_utthita_trikonasana.png",
  "Parivritta Trikonasana": "/asanas/04_parivritta_trikonasana.png",
  "Utthita Parsvakonasana": "/asanas/05_utthita_parsvakonasana.png",
  "Parivritta Parsvakonasana": "/asanas/06_parivritta_parsvakonasana.png",
  "Prasarita Padottanasana A": "/asanas/07_prasarita_padottanasana_a.png",
  "Prasarita Padottanasana B": "/asanas/08_prasarita_padottanasana_b.png",
  "Prasarita Padottanasana C": "/asanas/09_prasarita_padottanasana_c.png",
  "Prasarita Padottanasana D": "/asanas/10_prasarita_padottanasana_d.png",
  "Parsvottanasana": "/asanas/11_parsvottanasana.png",
  "Utthita Hasta Padangusthasana A": "/asanas/12_utthita_hasta_padangusthasana_a.png",
  "Utthita Hasta Padangusthasana B": "/asanas/13_utthita_hasta_padangusthasana_b.png",
  "Utthita Hasta Padangusthasana C": "/asanas/14_utthita_hasta_padangusthasana_c.png",
  "Utthita Hasta Padangusthasana D": "/asanas/15_utthita_hasta_padangusthasana_d.png",
  "Ardha Baddha Padmottanasana": "/asanas/16_ardha_baddha_padmottanasana.png",
  "Utkatasana": "/asanas/17_utkatasana.png",
  "Virabhadrasana A": "/asanas/18_virabhadrasana_a.png",
  "Virabhadrasana B": "/asanas/19_virabhadrasana_b.png",
  "Dandasana": "/asanas/20_dandasana.png",
  "Paschimottanasana A": "/asanas/21_paschimottanasana_a.png",
  "Paschimottanasana B": "/asanas/22_paschimottanasana_b.png",
  "Paschimottanasana C": "/asanas/23_paschimottanasana_c.png",
  "Purvottanasana": "/asanas/24_purvottanasana.png",
  "Ardha Baddha Padma Paschimottanasana": "/asanas/25_ardha_baddha_padma_paschimottanasana.png",
  "Trianga Mukhaikapada Paschimottanasana": "/asanas/26_trianga_mukhaikapada_paschimottanasana.png",
  "Janu Sirsasana A": "/asanas/27_janu_sirsasana_a.png",
  "Janu Sirsasana B": "/asanas/28_janu_sirsasana_b.png",
  "Janu Sirsasana C": "/asanas/29_janu_sirsasana_c.png",
  "Marichyasana A": "/asanas/30_marichyasana_a.png",
  "Marichyasana B": "/asanas/31_marichyasana_b.png",
  "Marichyasana C": "/asanas/32_marichyasana_c.png",
  "Marichyasana D": "/asanas/33_marichyasana_d.png",
  "Navasana (5 volte)": "/asanas/34_navasana_5_volte.png",
  "Bhujapidasana": "/asanas/35_bhujapidasana.png",
  "Kurmasana": "/asanas/36_kurmasana.png",
  "Supta Kurmasana": "/asanas/37_supta_kurmasana.png",
  "Garbha Pindasana": "/asanas/38_garbha_pindasana.png",
  "Kukkutasana": "/asanas/39_kukkutasana.png",
  "Baddha Konasana A": "/asanas/40_baddha_konasana_a.png",
  "Baddha Konasana B": "/asanas/41_baddha_konasana_b.png",
  "Upavishta Konasana A": "/asanas/42_upavishta_konasana_a.png",
  "Upavishta Konasana B": "/asanas/43_upavishta_konasana_b.png",
  "Supta Konasana": "/asanas/44_supta_konasana.png",
  "Supta Padangusthasana A": "/asanas/45_supta_padangusthasana_a.png",
  "Supta Padangusthasana B": "/asanas/46_supta_padangusthasana_b.png",
  "Supta Padangusthasana C": "/asanas/47_supta_padangusthasana_c.png",
  "Ubhaya Padangusthasana": "/asanas/48_ubhaya_padangusthasana.png",
  "Urdhva Mukha Paschimottanasana": "/asanas/49_urdhva_mukha_paschimottanasana.png",
  "Setu Bandhasana": "/asanas/50_setu_bandhasana.png",
  "Urdhva Dhanurasana (3 volte)": "/asanas/51_urdhva_dhanurasana_3_volte.png",
  "Paschimottanasana": "/asanas/52_paschimottanasana.png",
  "Sarvangasana": "/asanas/53_sarvangasana.png",
  "Halasana": "/asanas/54_halasana.png",
  "Karnapidasana": "/asanas/55_karnapidasana.png",
  "Urdhva Padmasana": "/asanas/56_urdhva_padmasana.png",
  "Pindasana": "/asanas/57_pindasana.png",
  "Matsyasana": "/asanas/58_matsyasana.png",
  "Uttana Padasana": "/asanas/59_uttana_padasana.png",
  "Sirsasana A": "/asanas/60_sirsasana_a.png",
  "Sirsasana B": "/asanas/61_sirsasana_b.png",
  "Baddha Padmasana": "/asanas/62_baddha_padmasana.png",
  "Padmasana": "/asanas/63_padmasana.png",
  "Tolasana": "/asanas/64_tolasana.png",
  "Savasana": "/asanas/65_savasana.png",
  "Surya Namaskara A": "/asanas/66_surya_namaskara_a.png",
  "Surya Namaskara B": "/asanas/67_surya_namaskara_b.png",
};
